### ISSUE TITLE
munin: split into different tools

### ISSUE THREAD

**Issue by blshkv** [repology/repology-rules#198]
https://repology.org/project/munin/versions
https://github.com/Neo23x0/munin
http://munin-monitoring.org/ (https://github.com/munin-monitoring/munin/releases)

also, it is not clear why wikidata shows "2.99.3" as the latest version

**Comment by blshkv** [comment]
ping? Is everything fine at your end? I'm so used to your quick turnbacks.

**Comment by AMDmi3** [comment]
I'm currently on vacation. Btw, I'd be grateful for PRs instead of issues in future. Not only this saves time for other things, but I also can merge them from anywhere.

**Comment by blshkv** [comment]
I know it might sound easy for you, but I'm still puzzled with rules and have no time to figure out what is the right place to fix it. 

Have a good holiday, come back fresh and fix it any convenient time!

Cheers

**Comment by AMDmi3** [comment]
Version should be fixed. To split this, pentoo should provide homepage information.

**Comment by blshkv** [comment]
Sorry, the problem is not fixed. We provided homepage info but the problem is that file is a symlink.
https://github.com/pentoo/pentoo-overlay/blob/master/net-misc/munin/munin-0.14.1.ebuild
https://github.com/pentoo/pentoo-overlay/blob/master/net-misc/munin/munin-9999.ebuild

So repology is not able to follow it:
https://raw.githubusercontent.com/pentoo/pentoo-overlay/master/net-misc/munin/munin-0.14.1.ebuild

Is any way you can fix it?

**Comment by blshkv** [comment]
Great. Thanks!
